name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: ./install-dependencies.sh
    - name: make
      run: make build/example-glpk
    - name: run
      run: ./build/example-glpk
    - uses: actions/upload-artifact@v2
      with:
        name: libosiglpk.a
        path: build/libosiglpk.a
